### ISSUE TITLE
low-g quartile stats need to be updated

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#26]
the quartile stats need to be updated: https://github.com/alejocosmico/NIRSpecFigures/blob/master/data/quartiles_stats.txt
it's ok with me to leave beta and gammas together, but you can separate them if you want. problem with that is that it impacts the JK box and whisker...I vote for keeping them together. Call it L0b + L0g and L1b+L1g.

**Comment by alejocosmico** [comment]
Done. I left gammas and betas together.

**Comment by kelle** [comment]
Cats and dogs living together!

On Tuesday, June 30, 2015, alejocosmico <notifications@github.com> wrote:

> Done. I left gammas and betas together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alejocosmico/NIRSpecFigures/issues/26#issuecomment-117308683>
> .
>


-- 
kelle
(via iOS)

**Comment by kelle** [comment]
sorry, something still isn't quite right:
- L1 lowg should be 5 (3 gammas + 2 betas) not 4
- L2 lowg should be 2 not 3.

**Comment by alejocosmico** [comment]
Done. The issue was 0055+1634, which on the tables was showing up as L2 instead of L1.5. Now the plot and stats are updated.

**Comment by alejocosmico** [comment]
Quartiles are now updated.

**Comment by kelle** [comment]
I want to list the stats in the table for the gamma and beta separately. Could you just tell me what function you used in python and I can do this by hand?

**Comment by alejocosmico** [comment]
The code that does it is jk_plot_kc.py. It reads the input table OptNIR_ALL.txt, using the column "NStars Publication.Table" to discriminate between field and low gravity stars. The entry on that table starts with a category number:
3= field star used in template
4= field star not used in template
5= low g star used in template
6= low g star not used in template.

This code also creates the JK.pdf figure. It is when the code plots the boxplots that the stats are calculated. The boxplots are generated in line 74 (object called "bp"), the relevant stats are extracted in lines 103-110, and they are then stored  in the file "quartile_stats.txt" in line 111.

This code could be modified to calculate the stats for beta and gamma separately, although it would require to use an additional column from the input table to be able to distinguish between beta and gama objects. Not difficult but it would take me a couple of days to do it.

Alternatively, one could choose only the beta or gamma rows from the input table manually, plot them using plotbox in matplotlib, and then read the stats just as I did it in the code.

Let me know how you want to proceed.

**Comment by kelle** [comment]
I don’t want to change the code nor the figures. the number of objects is
very small and I just want to calculate the quartile ranges by hand…by just
typing into terminal without scripting. and then I will type them into the
latex table by hand.   What is the python function that you use to find the
quartile ranges?

Kelle

On Mon, Jan 25, 2016 at 4:01 PM, Alejandro Núñez <notifications@github.com>
wrote:

> The code that does it is jk_plot_kc.py. It reads the input table
> OptNIR_ALL.txt, using the column "NStars Publication.Table" to discriminate
> between field and low gravity stars. The entry on that table starts with a
> category number:
> 3= field star used in template
> 4= field star not used in template
> 5= low g star used in template
> 6= low g star not used in template.
>
> This code also creates the JK.pdf figure. It is when the code plots the
> boxplots that the stats are calculated. The boxplots are generated in line
> 74 (object called "bp"), the relevant stats are extracted in lines 103-110,
> and they are then stored in the file "quartile_stats.txt" in line 111.
>
> This code could be modified to calculate the stats for beta and gamma
> separately, although it would require to use an additional column from the
> input table to be able to distinguish between beta and gama objects. Not
> difficult but it would take me a couple of days to do it.
>
> Alternatively, one could choose only the beta or gamma rows from the input
> table manually, plot them using plotbox in matplotlib, and then read the
> stats just as I did it in the code.
>
> Let me know how you want to proceed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alejocosmico/NIRSpecFigures/issues/26#issuecomment-174661428>
> .
>



-- 
Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by alejocosmico** [comment]
In my code the quartile ranges are calculated by the matplotlib boxplot function. One option is to draw the boxplots (on a temporary figure) and then read the quartiles from the resulting object (as explained before). 
Probably a better option is to use the numpy function "percentile" (http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.percentile.html), which looks pretty straightforward to use (just use q=25, 50, and 75). Let me know if it works out OK.

**Comment by kelle** [comment]
here's the code I'm writing: https://github.com/alejocosmico/NIRSpecFigures/blob/master/code/Young_JKcolor_quartiles.ipynb

**Comment by kelle** [comment]
If you know the correct syntax to find the average, that would be helpful. Can just type here and I'll implement. :)

**Comment by alejocosmico** [comment]
The average is not working because you entered LObeta_JK with the letter O, and not the number zero (I think). In principle, np.average should work; no need to convert it to list. Give it a try and let me know.

**Comment by kelle** [comment]
okey dokey, all done. :)
